[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
roog_contract = "6NchgAdLqvbXafnsHobsvPsaepA9QDh5ccsWVcbBRojx"

[programs.devnet]
roog_contract = "6NchgAdLqvbXafnsHobsvPsaepA9QDh5ccsWVcbBRojx"

[programs.mainnet]
roog_contract = "6NchgAdLqvbXafnsHobsvPsaepA9QDh5ccsWVcbBRojx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
