[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
roog_contract = "6NchgAdLqvbXafnsHobsvPsaepA9QDh5ccsWVcbBRojx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wonder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
